on:
  push:
    tags: 
      - '*.*.*'

name: Publish Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup Node
        uses: actions/setup-node@latest
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@latest
        with: 
          files: |
            main.js
            styles.css
            manifest.json
